// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.3
package com.aszender.contracts.inventory.v1;

public final class InventoryProto {
  private InventoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aszender_inventory_v1_ReserveStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aszender_inventory_v1_ReserveStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aszender_inventory_v1_ReserveItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aszender_inventory_v1_ReserveItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aszender_inventory_v1_ReserveStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aszender_inventory_v1_ReserveStockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\031com.aszender.inventor" +
      "y.v1\"^\n\023ReserveStockRequest\022\020\n\010order_id\030" +
      "\001 \001(\003\0225\n\005items\030\002 \003(\0132&.com.aszender.inve" +
      "ntory.v1.ReserveItem\"3\n\013ReserveItem\022\022\n\np" +
      "roduct_id\030\001 \001(\003\022\020\n\010quantity\030\002 \001(\005\"8\n\024Res" +
      "erveStockResponse\022\020\n\010reserved\030\001 \001(\010\022\016\n\006r" +
      "eason\030\002 \001(\t2\203\001\n\020InventoryService\022o\n\014Rese" +
      "rveStock\022..com.aszender.inventory.v1.Res" +
      "erveStockRequest\032/.com.aszender.inventor" +
      "y.v1.ReserveStockResponseB7\n#com.aszende" +
      "r.contracts.inventory.v1B\016InventoryProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_aszender_inventory_v1_ReserveStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aszender_inventory_v1_ReserveStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aszender_inventory_v1_ReserveStockRequest_descriptor,
        new java.lang.String[] { "OrderId", "Items", });
    internal_static_com_aszender_inventory_v1_ReserveItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aszender_inventory_v1_ReserveItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aszender_inventory_v1_ReserveItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", });
    internal_static_com_aszender_inventory_v1_ReserveStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_aszender_inventory_v1_ReserveStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aszender_inventory_v1_ReserveStockResponse_descriptor,
        new java.lang.String[] { "Reserved", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
