// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.3
package com.aszender.contracts.inventory.v1;

public interface ReserveStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aszender.inventory.v1.ReserveStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 order_id = 1;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  java.util.List<com.aszender.contracts.inventory.v1.ReserveItem> 
      getItemsList();
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  com.aszender.contracts.inventory.v1.ReserveItem getItems(int index);
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  java.util.List<? extends com.aszender.contracts.inventory.v1.ReserveItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  com.aszender.contracts.inventory.v1.ReserveItemOrBuilder getItemsOrBuilder(
      int index);
}
