// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.3
package com.aszender.contracts.inventory.v1;

/**
 * Protobuf type {@code com.aszender.inventory.v1.ReserveStockRequest}
 */
public final class ReserveStockRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.aszender.inventory.v1.ReserveStockRequest)
    ReserveStockRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReserveStockRequest.newBuilder() to construct.
  private ReserveStockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReserveStockRequest() {
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReserveStockRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aszender.contracts.inventory.v1.InventoryProto.internal_static_com_aszender_inventory_v1_ReserveStockRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aszender.contracts.inventory.v1.InventoryProto.internal_static_com_aszender_inventory_v1_ReserveStockRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aszender.contracts.inventory.v1.ReserveStockRequest.class, com.aszender.contracts.inventory.v1.ReserveStockRequest.Builder.class);
  }

  public static final int ORDER_ID_FIELD_NUMBER = 1;
  private long orderId_ = 0L;
  /**
   * <code>int64 order_id = 1;</code>
   * @return The orderId.
   */
  @java.lang.Override
  public long getOrderId() {
    return orderId_;
  }

  public static final int ITEMS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.aszender.contracts.inventory.v1.ReserveItem> items_;
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.aszender.contracts.inventory.v1.ReserveItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aszender.contracts.inventory.v1.ReserveItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  @java.lang.Override
  public com.aszender.contracts.inventory.v1.ReserveItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
   */
  @java.lang.Override
  public com.aszender.contracts.inventory.v1.ReserveItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (orderId_ != 0L) {
      output.writeInt64(1, orderId_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(2, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (orderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, orderId_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aszender.contracts.inventory.v1.ReserveStockRequest)) {
      return super.equals(obj);
    }
    com.aszender.contracts.inventory.v1.ReserveStockRequest other = (com.aszender.contracts.inventory.v1.ReserveStockRequest) obj;

    if (getOrderId()
        != other.getOrderId()) return false;
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOrderId());
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aszender.contracts.inventory.v1.ReserveStockRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aszender.contracts.inventory.v1.ReserveStockRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.aszender.inventory.v1.ReserveStockRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.aszender.inventory.v1.ReserveStockRequest)
      com.aszender.contracts.inventory.v1.ReserveStockRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aszender.contracts.inventory.v1.InventoryProto.internal_static_com_aszender_inventory_v1_ReserveStockRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aszender.contracts.inventory.v1.InventoryProto.internal_static_com_aszender_inventory_v1_ReserveStockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aszender.contracts.inventory.v1.ReserveStockRequest.class, com.aszender.contracts.inventory.v1.ReserveStockRequest.Builder.class);
    }

    // Construct using com.aszender.contracts.inventory.v1.ReserveStockRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      orderId_ = 0L;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aszender.contracts.inventory.v1.InventoryProto.internal_static_com_aszender_inventory_v1_ReserveStockRequest_descriptor;
    }

    @java.lang.Override
    public com.aszender.contracts.inventory.v1.ReserveStockRequest getDefaultInstanceForType() {
      return com.aszender.contracts.inventory.v1.ReserveStockRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.aszender.contracts.inventory.v1.ReserveStockRequest build() {
      com.aszender.contracts.inventory.v1.ReserveStockRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aszender.contracts.inventory.v1.ReserveStockRequest buildPartial() {
      com.aszender.contracts.inventory.v1.ReserveStockRequest result = new com.aszender.contracts.inventory.v1.ReserveStockRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aszender.contracts.inventory.v1.ReserveStockRequest result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(com.aszender.contracts.inventory.v1.ReserveStockRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.orderId_ = orderId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aszender.contracts.inventory.v1.ReserveStockRequest) {
        return mergeFrom((com.aszender.contracts.inventory.v1.ReserveStockRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aszender.contracts.inventory.v1.ReserveStockRequest other) {
      if (other == com.aszender.contracts.inventory.v1.ReserveStockRequest.getDefaultInstance()) return this;
      if (other.getOrderId() != 0L) {
        setOrderId(other.getOrderId());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000002);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              orderId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.aszender.contracts.inventory.v1.ReserveItem m =
                  input.readMessage(
                      com.aszender.contracts.inventory.v1.ReserveItem.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long orderId_ ;
    /**
     * <code>int64 order_id = 1;</code>
     * @return The orderId.
     */
    @java.lang.Override
    public long getOrderId() {
      return orderId_;
    }
    /**
     * <code>int64 order_id = 1;</code>
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(long value) {

      orderId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 order_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      orderId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.aszender.contracts.inventory.v1.ReserveItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        items_ = new java.util.ArrayList<com.aszender.contracts.inventory.v1.ReserveItem>(items_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aszender.contracts.inventory.v1.ReserveItem, com.aszender.contracts.inventory.v1.ReserveItem.Builder, com.aszender.contracts.inventory.v1.ReserveItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public java.util.List<com.aszender.contracts.inventory.v1.ReserveItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public com.aszender.contracts.inventory.v1.ReserveItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder setItems(
        int index, com.aszender.contracts.inventory.v1.ReserveItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder setItems(
        int index, com.aszender.contracts.inventory.v1.ReserveItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder addItems(com.aszender.contracts.inventory.v1.ReserveItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder addItems(
        int index, com.aszender.contracts.inventory.v1.ReserveItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder addItems(
        com.aszender.contracts.inventory.v1.ReserveItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder addItems(
        int index, com.aszender.contracts.inventory.v1.ReserveItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.aszender.contracts.inventory.v1.ReserveItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public com.aszender.contracts.inventory.v1.ReserveItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public com.aszender.contracts.inventory.v1.ReserveItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public java.util.List<? extends com.aszender.contracts.inventory.v1.ReserveItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public com.aszender.contracts.inventory.v1.ReserveItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.aszender.contracts.inventory.v1.ReserveItem.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public com.aszender.contracts.inventory.v1.ReserveItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.aszender.contracts.inventory.v1.ReserveItem.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aszender.inventory.v1.ReserveItem items = 2;</code>
     */
    public java.util.List<com.aszender.contracts.inventory.v1.ReserveItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aszender.contracts.inventory.v1.ReserveItem, com.aszender.contracts.inventory.v1.ReserveItem.Builder, com.aszender.contracts.inventory.v1.ReserveItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aszender.contracts.inventory.v1.ReserveItem, com.aszender.contracts.inventory.v1.ReserveItem.Builder, com.aszender.contracts.inventory.v1.ReserveItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.aszender.inventory.v1.ReserveStockRequest)
  }

  // @@protoc_insertion_point(class_scope:com.aszender.inventory.v1.ReserveStockRequest)
  private static final com.aszender.contracts.inventory.v1.ReserveStockRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aszender.contracts.inventory.v1.ReserveStockRequest();
  }

  public static com.aszender.contracts.inventory.v1.ReserveStockRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReserveStockRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReserveStockRequest>() {
    @java.lang.Override
    public ReserveStockRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReserveStockRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReserveStockRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aszender.contracts.inventory.v1.ReserveStockRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

