// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.3
package com.aszender.contracts.inventory.v1;

public interface ReserveStockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aszender.inventory.v1.ReserveStockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool reserved = 1;</code>
   * @return The reserved.
   */
  boolean getReserved();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
