// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.3
package com.aszender.contracts.inventory.v1;

public interface ReserveItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aszender.inventory.v1.ReserveItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
